apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: mycluster
servers: 1
agents: 3
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: myregistry
    host: "0.0.0.0"
    hostPort: "5000"
